services:
  kafka-consumer:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
    networks:
      - ketchapp-net

networks:
  ketchapp-net:
    external: true
